<img src="https://user-images.githubusercontent.com/7065401/75165824-badf4680-5701-11ea-9c5b-5475b0a33abf.png"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

Es una librería de Python diseñada para facilitar el manejo y análisis de datos. Construida sobre NumPy, Pandas extiende sus capacidades, proporcionando estructuras de datos y funciones avanzadas que permiten una manipulación más flexible y eficiente de datos tabulares y de series temporales.

[Documentacion](https://pandas.pydata.org/docs/)

In [ ]:
!pip install pandas -q

In [ ]:
import numpy as np
import pandas as pd

### 1. Release

In [ ]:
pd.__version__

'2.2.3'

## 2. Estructuras de Datos

Dos estrucutras de datos principales:

* Series
* DataFrame

## 3. Pandas - Series

Vamos a analizar el G7, el cual es un partido político formado por Canadá, Francia, Alemania, Italia, Japón, Reino Unido y Estados Unidos. Comenzaremos analizando la población y para ello usaremos un objeto `pandas.Series`.

In [ ]:
# En millones
g7_poblacion = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [ ]:
g7_poblacion

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [ ]:
g7_poblacion[1]

np.float64(63.951)

### 3.1 Nombre de la serie

La Serie puede tener un nombre, para documentar mejor el propósito de la Serie.

In [ ]:
g7_poblacion.name = 'G7 Poblacion en millones'

In [ ]:
g7_poblacion

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: G7 Poblacion en millones, dtype: float64

### 3.2 Relación con numpy

Son muy parecidas a los arrays en NumPy.

In [ ]:
# tipo de datos
g7_poblacion.dtype

dtype('float64')

In [ ]:
# valores
g7_poblacion.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

De hecho se almacenan en numpy arrays

In [ ]:
# type
type(g7_poblacion.values)

numpy.ndarray

Si bien son parecidas a las listas en Python o a los Arrays de NumPy, son mas parecidas a los diccionarios de Python.

In [ ]:
# un indice que seria la clave y un valor
g7_poblacion

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: G7 Poblacion en millones, dtype: float64

### 3.3 Acceso a los valores

In [ ]:
# acceso por indice
g7_poblacion[0]

np.float64(35.467)

In [ ]:
g7_poblacion[1]

np.float64(63.951)

In [ ]:
g7_poblacion.index

RangeIndex(start=0, stop=7, step=1)

A diferencia de las listas en Python, podemos definir un valor a cada indice

In [ ]:
g7_poblacion.index = [
    'Canada',
    'Francia',
    'Alemania',
    'Italia',
    'Japon',
    'Reino Unido',
    'Estados Unidos',
]

In [ ]:
g7_poblacion

Canada             35.467
Francia            63.951
Alemania           80.940
Italia             60.665
Japon             127.061
Reino Unido        64.511
Estados Unidos    318.523
Name: G7 Poblacion en millones, dtype: float64

In [ ]:
g7_poblacion['Canada']

np.float64(35.467)

In [ ]:
g7_poblacion['Japon']

np.float64(127.061)

In [ ]:
g7_poblacion.index

Index(['Canada', 'Francia', 'Alemania', 'Italia', 'Japon', 'Reino Unido',
       'Estados Unidos'],
      dtype='object')

### 3.4 Creación

Creación de series I

In [ ]:
# a partir de un diccionario - nombre de la serie
nueva_forma = pd.Series({
    'Canada': 35.467,
    'Francia': 63.951,
    'Alemenia': 80.94,
    'Italia': 60.665,
    'Japon': 127.061,
    'Reino Unido': 64.511,
    'Estados Unidos': 318.523
}, name='G7 Poblacion en millones')

In [ ]:
nueva_forma

Canada             35.467
Francia            63.951
Alemenia           80.940
Italia             60.665
Japon             127.061
Reino Unido        64.511
Estados Unidos    318.523
Name: G7 Poblacion en millones, dtype: float64

Creación de Series II

In [ ]:
pd.Series(
    [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    index=['Canada', 'Francia', 'Alemania', 'Italia', 'Japon', 'Reino Unido',
       'Estados Unidos'],
    name='G7 Poblacion en millones')

Canada             35.467
Francia            63.951
Alemania           80.940
Italia             60.665
Japon             127.061
Reino Unido        64.511
Estados Unidos    318.523
Name: G7 Poblacion en millones, dtype: float64

Creación de Series III

Tambien se pueden crear series a partir de otras series, especificando los indices.

In [ ]:
g_nuevo = pd.Series(g7_poblacion, index=['Francia', 'Japon', 'Italia'])

In [ ]:
g_nuevo

Francia     63.951
Japon      127.061
Italia      60.665
Name: G7 Poblacion en millones, dtype: float64

In [ ]:
g_nuevo.name = "Nueva Serie"

In [ ]:
g_nuevo

Francia     63.951
Japon      127.061
Italia      60.665
Name: Nueva Serie, dtype: float64

### 3.5 Indexación

La indexacion funciona de manera similar a las listas y los diccionarios.
Se usa el indice del elemento a buscar:

In [ ]:
g7_poblacion

Canada             35.467
Francia            63.951
Alemania           80.940
Italia             60.665
Japon             127.061
Reino Unido        64.511
Estados Unidos    318.523
Name: G7 Poblacion en millones, dtype: float64

In [ ]:
g7_poblacion['Canada']

np.float64(35.467)

Con el atributo iloc accedemos a las posiciones con indices numericos:

In [ ]:
g7_poblacion.iloc[1]

np.float64(63.951)

In [ ]:
g7_poblacion.iloc[2]

np.float64(80.94)

Tambien es posible visualizar mas de un elemento a la vez (multiples indices)

In [ ]:
# indice Canada y Japon
g7_poblacion[['Canada', 'Japon']]

Canada     35.467
Japon     127.061
Name: G7 Poblacion en millones, dtype: float64

El resultado es una nueva Serie.

In [ ]:
g7_poblacion.iloc[[1, 4]]

Francia     63.951
Japon      127.061
Name: G7 Poblacion en millones, dtype: float64

Slicing es soportado por las Series. A diferencia de las listas, el limite superior, se incluye en el resultado

In [ ]:
g7_poblacion['Francia': 'Japon']

Francia      63.951
Alemania     80.940
Italia       60.665
Japon       127.061
Name: G7 Poblacion en millones, dtype: float64

### 3.6 Seleccion condicional

In [ ]:
g7_poblacion

Canada             35.467
Francia            63.951
Alemania           80.940
Italia             60.665
Japon             127.061
Reino Unido        64.511
Estados Unidos    318.523
Name: G7 Poblacion en millones, dtype: float64

Países con población mayor a 70 MM

In [ ]:
g7_poblacion > 70

Canada            False
Francia           False
Alemania           True
Italia            False
Japon              True
Reino Unido       False
Estados Unidos     True
Name: G7 Poblacion en millones, dtype: bool

In [ ]:
indices = g7_poblacion > 70
indices

Canada            False
Francia           False
Alemania           True
Italia            False
Japon              True
Reino Unido       False
Estados Unidos     True
Name: G7 Poblacion en millones, dtype: bool

In [ ]:
# g7_mayor70 = g7_poblacion[g7_poblacion > 70]
g7_mayor70 = g7_poblacion[indices]

In [ ]:
g7_mayor70

Alemania           80.940
Japon             127.061
Estados Unidos    318.523
Name: G7 Poblacion en millones, dtype: float64

Países con población mayor al promedio del conjunto

In [ ]:
g7_poblacion.mean()

np.float64(107.30257142857144)

In [ ]:
# paises con poblacion mayor a la media?
g7_poblacion > g7_poblacion.mean()

Canada            False
Francia           False
Alemania          False
Italia            False
Japon              True
Reino Unido       False
Estados Unidos     True
Name: G7 Poblacion en millones, dtype: bool

In [ ]:
g7_poblacion[g7_poblacion > g7_poblacion.mean()]

Japon             127.061
Estados Unidos    318.523
Name: G7 Poblacion en millones, dtype: float64

### 3.7 Operaciones matematicas

In [ ]:
g7_poblacion

Canada             35.467
Francia            63.951
Alemania           80.940
Italia             60.665
Japon             127.061
Reino Unido        64.511
Estados Unidos    318.523
Name: G7 Poblacion en millones, dtype: float64

In [ ]:
g7_poblacion * 1_000_000

Canada             35467000.0
Francia            63951000.0
Alemania           80940000.0
Italia             60665000.0
Japon             127061000.0
Reino Unido        64511000.0
Estados Unidos    318523000.0
Name: G7 Poblacion en millones, dtype: float64

In [ ]:
np.log(g7_poblacion)

Canada            3.568603
Francia           4.158117
Alemania          4.393708
Italia            4.105367
Japon             4.844667
Reino Unido       4.166836
Estados Unidos    5.763695
Name: G7 Poblacion en millones, dtype: float64

In [ ]:
g7_poblacion / 1_000_000

Canada            0.000035
Francia           0.000064
Alemania          0.000081
Italia            0.000061
Japon             0.000127
Reino Unido       0.000065
Estados Unidos    0.000319
Name: G7 Poblacion en millones, dtype: float64

###  3.8 Modificando la serie

In [ ]:
# Agregar un nuevo valor a la serie
g7_poblacion['Argentina'] = 45

In [ ]:
g7_poblacion

Canada             35.467
Francia            63.951
Alemania           80.940
Italia             60.665
Japon             127.061
Reino Unido        64.511
Estados Unidos    318.523
Argentina          45.000
Name: G7 Poblacion en millones, dtype: float64

In [ ]:
# modificar valores en la serie
g7_poblacion[g7_poblacion < g7_poblacion.mean()] = 99.9

In [ ]:
g7_poblacion < g7_poblacion.mean()

Canada             True
Francia            True
Alemania           True
Italia             True
Japon             False
Reino Unido        True
Estados Unidos    False
Argentina          True
Name: G7 Poblacion en millones, dtype: bool

In [ ]:
g7_poblacion.mean()

In [ ]:
g7_poblacion

Canada             99.900
Francia            99.900
Alemania           99.900
Italia             99.900
Japon             127.061
Reino Unido        99.900
Estados Unidos    318.523
Argentina          99.900
Name: G7 Poblacion en millones, dtype: float64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)