

<img src="https://user-images.githubusercontent.com/7065401/39117440-24199c72-46e7-11e8-8ffc-25c6e27e07d4.jpg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Manejo de datos faltantes con Pandas

Pandas toma prestadas todas las capacidades de Numpy y agrega una serie de métodos convenientes para manejar los valores faltantes.

![separator2](https://i.imgur.com/4gX5WFr.png)

In [ ]:
# importamos las librerias
import numpy as np
import pandas as pd

### Funciones de utilidad en Pandas

De manera similar a numpy, pandas también tiene algunas funciones para identificar y detectar valores nulos:

In [ ]:
# isnull
pd.isnull(np.nan)

True

In [ ]:
pd.isnull(None)

True

In [ ]:
pd.isnull(6)

False

In [ ]:
# isna
pd.isna(np.nan)

True

In [ ]:
pd.isna(5)

False

La función opuesta también existe:

In [ ]:
# notnull
pd.notnull(None)

False

In [ ]:
pd.notnull(np.nan)

False

In [ ]:
pd.notnull(10)

True

Estas funciones se pueden utilizar tanto en `Series` como en `DataFrame`s:

In [ ]:
# serie - isnull
x = pd.Series([1, np.nan, 7])
x

0    1.0
1    NaN
2    7.0
dtype: float64

In [ ]:
pd.isnull(x)

0    False
1     True
2    False
dtype: bool

In [ ]:
# serie - notnull
pd.notnull(x)

0     True
1    False
2     True
dtype: bool

In [ ]:
# dataframe
y = pd.DataFrame({
    'Columna A': [1, np.nan, 7],
    'Columna B': [np.nan, 2, 3],
    'Columna C': [np.nan, 2, np.nan]
})
y

   Columna A  Columna B  Columna C
0        1.0        NaN        NaN
1        NaN        2.0        2.0
2        7.0        3.0        NaN

In [ ]:
# dataframe - isnull
pd.isnull(y)

   Columna A  Columna B  Columna C
0      False       True       True
1       True      False      False
2      False      False       True

In [ ]:
# dataframe - notnull
pd.notnull(y)

   Columna A  Columna B  Columna C
0       True      False      False
1      False       True       True
2       True       True      False

![separator1](https://i.imgur.com/ZUWYTii.png)

### Operaciones con datos faltantes


Pandas administra los valores faltantes de una forma diferente a numpy. Los valores 'nan's ya no se comportarán como un "virus", y las operaciones simplemente los ignorarán por completo:

In [ ]:
pd.Series([1, 2, 4, np.nan, np.nan]).count()

np.int64(3)

In [ ]:
# suma los valores de la serie
pd.Series([1, 2, 4, np.nan, np.nan]).sum()

np.float64(7.0)

In [ ]:
pd.Series([1, 2, np.nan, np.nan]).mean()

np.float64(1.5)

### Eliminando datos faltantes

Como vimos en numpy, podremos combinar la "seleccion booleana" + `pd.isnull` para filtrar los valores nulos y nan:

In [ ]:
# definimos una serie
s = pd.Series([1, 2, 3, np.nan, np.nan, 4])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [ ]:
pd.notnull(s)

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [ ]:
pd.isnull(s)

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [ ]:
# cuantos no nulos
pd.notnull(s).sum()

np.int64(4)

In [ ]:
# cuantos nulos
pd.isnull(s).sum()

np.int64(2)

In [ ]:
s

In [ ]:
# sin los nulos -- nota: ver los indices
s[pd.notnull(s)]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

Como ambos métodos `notnull` y `isnull` son métodos de `Series` y `DataFrame`s, podemos usarlos de la siguiente manera:

In [ ]:
s.notnull()

In [ ]:
# usamos la seleccion booleana
s[s.notnull()]

![separator1](https://i.imgur.com/ZUWYTii.png)

### Eliminando valores nulos en Series

En este caso podemos usar el método `dropna`:

In [ ]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [ ]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

Retorna una nueva serie sin los valores nulos.

### Eliminando valores nulos en DataFrames

Vimos lo sencillo que fue eliminar los valores `na` en las Series. En los `DataFrame`s,
habra que considerar algunas cosas, porque no se pueden eliminar valores individuales. Se pueden eliminar filas o columnas. Veamos el siguiente `DataFrame`:

In [ ]:
df = pd.DataFrame({
    'Columna A': [1, np.nan, 30, np.nan],
    'Columna B': [2, 8, 31, np.nan],
    'Columna C': [np.nan, 9, 32, 100],
    'Columna D': [5, 8, 34, 110],
})

In [ ]:
df

   Columna A  Columna B  Columna C  Columna D
0        1.0        2.0        NaN          5
1        NaN        8.0        9.0          8
2       30.0       31.0       32.0         34
3        NaN        NaN      100.0        110

In [ ]:
df.shape

(4, 4)

In [ ]:
# informacion de no nulos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Columna A  2 non-null      float64
 1   Columna B  3 non-null      float64
 2   Columna C  3 non-null      float64
 3   Columna D  4 non-null      int64
dtypes: float64(3), int64(1)
memory usage: 260.0 bytes

In [ ]:
df.isnull()

   Columna A  Columna B  Columna C  Columna D
0      False      False       True      False
1       True      False      False      False
2      False      False      False      False
3       True       True      False      False

In [ ]:
# cantidad de nulos por columna
df.isnull().sum()

Columna A    2
Columna B    1
Columna C    1
Columna D    0
dtype: int64

El comportamiento predeterminado de `dropna` eliminará todas las filas en las que este presente  _cualquier_ valor nulo:

In [ ]:
df.dropna()

   Columna A  Columna B  Columna C  Columna D
2       30.0       31.0       32.0         34

En este caso estamos quitando las **filas** que contienen valores nulos. Podemos utilizar el parámetros `axis` para eliminar las columnas que tienen valores nulos:

In [ ]:
df.dropna(axis='columns')  # axis='rows' tambien funciona

   Columna D
0          5
1          8
2         34
3        110

En este caso, se quitará cualquier fila o columna que contenga **al menos** un valor nulo. Lo cual puede ser, según el caso, demasiado extremo. Se puede controlar este comportamiento con el parámetro 'how'. Puede ser `'cualquiera'` or `'todos'`'':

In [ ]:
df2 = pd.DataFrame({
    'Columna A': [1, np.nan, 30],
    'Columna B': [2, np.nan, 31],
    'Columna C': [np.nan, np.nan, 100]
})

In [ ]:
df2

   Columna A  Columna B  Columna C
0        1.0        2.0        NaN
1        NaN        NaN        NaN
2       30.0       31.0      100.0

In [ ]:
# all: las filas que tienen todos los valores NaN
df2.dropna(how='all')

   Columna A  Columna B  Columna C
0        1.0        2.0        NaN
2       30.0       31.0      100.0

In [ ]:
# any (default): al menos un nan
df2.dropna(how='any')

   Columna A  Columna B  Columna C
2       30.0       31.0      100.0

También se puede usar el parámetro `thresh` para indicar un umbral _threshold_ (numero minimo) de valores **no nulos** para la fila/columna que se pueden mantener:

In [ ]:
df2

   Columna A  Columna B  Columna C
0        1.0        2.0        NaN
1        NaN        NaN        NaN
2       30.0       31.0      100.0

In [ ]:
# si la fila tiene al menos un valor no nulo se corserva
df2.dropna(thresh=1)

   Columna A  Columna B  Columna C
0        1.0        2.0        NaN
2       30.0       31.0      100.0

In [ ]:
df2.dropna(thresh=1, axis='columns')

   Columna A  Columna B  Columna C
0        1.0        2.0        NaN
1        NaN        NaN        NaN
2       30.0       31.0      100.0

In [ ]:
df2.dropna(thresh=2, axis='columns')

   Columna A  Columna B
0        1.0        2.0
1        NaN        NaN
2       30.0       31.0

![separator1](https://i.imgur.com/ZUWYTii.png)

### Reemplazando los valores nulos

A veces, en lugar de eliminar los valores nulos, es posible que necesitemos reemplazarlos con algún otro valor. Esto depende en gran medida del contexto y del conjunto de datos con el que esté trabajando actualmente. A veces, un `nan` se puede reemplazar con un `0`, a veces se puede reemplazar con la `media` de la muestra, y otras veces se puede tomar el valor más cercano. De nuevo, depende del contexto. Le mostraremos los diferentes métodos y mecanismos y luego podrá aplicarlos a su propio problema.

In [ ]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

**Completando valores nulos con valores arbitrarios**

In [ ]:
# completa con 0
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    0.0
5    4.0
dtype: float64

In [ ]:
s.mean()

np.float64(2.5)

In [ ]:
# con la media
s.fillna(s.mean())

0    1.0
1    2.0
2    3.0
3    2.5
4    2.5
5    4.0
dtype: float64

In [ ]:
s.fillna(s.median())

0    1.0
1    2.0
2    3.0
3    2.5
4    2.5
5    4.0
dtype: float64

**Completando valores nulos con valores cercanos**

El argumento `method` especifica con que valor cercano completar el valor nulo:

In [ ]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [ ]:
# fillna: rellena con el primer valor anterior al no nulo -- propaga hacia adelante
s.fillna(method='ffill')

/tmp/ipykernel_2835/1408101508.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method='ffill')

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [ ]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [ ]:
# ffill: va a completar con el valor mas cercano superior al no nulo
s.ffill()

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [ ]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [ ]:
# bfill: lo opuesto a ffill
s.bfill()

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    4.0
dtype: float64

Estos métodos pueden dejar valores nulos en los extremos de las Series/DataFrame:

In [ ]:
pd.Series([np.nan, 3, np.nan, 9]).ffill()

0    NaN
1    3.0
2    3.0
3    9.0
dtype: float64

In [ ]:
pd.Series([np.nan, 3, np.nan, 9]).bfill()

0    3.0
1    3.0
2    9.0
3    9.0
dtype: float64

In [ ]:
pd.Series([1, np.nan, 3, np.nan, np.nan]).bfill()

0    1.0
1    3.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [ ]:
pd.Series([1, np.nan, 3, np.nan, np.nan]).ffill()

0    1.0
1    1.0
2    3.0
3    3.0
4    3.0
dtype: float64

### Completando valores nulos en DataFrames

El método `fillna` también funciona en `DataFrame's`.Las principales diferencias son que se puede especificar el `eje` (como de costumbre, filas o columnas) a usar para rellenar los valores.

In [ ]:
df

In [ ]:
# con un valor especifico por columna
df.fillna({'Columna A': 0, 'Columna B': 99, 'Columna C': df['Columna C'].mean()})

In [ ]:
df

In [ ]:
# recorre filas y completa con valores de columna
df.ffill(axis='rows')

In [ ]:
df

In [ ]:
df.ffill(axis='columns')

In [ ]:
df.bfill(axis='columns')

![separator1](https://i.imgur.com/ZUWYTii.png)

### Verificando si hay valores nulos (NAs)

La pregunta es: ¿Esta `Serie` o `DataFrame` contiene algún valor nulo? La respuesta debe ser sí o no: `Verdadero` o `Falso`. ¿Cómo puedes verificarlo?

**Ejemplo 1: comparando la longitud**

Si hay valores nulos, `s.dropna()` sera menor que `s`:

In [ ]:
s

El método `count` excluye los valores `nan`s en su respuesta:

In [ ]:
s.count()

In [ ]:
len(s)

Podríamos hacer:

In [ ]:
missing_values = len(s.dropna()) != len(s)
missing_values

**Otra forma**

Los métodos `any` y `all` verifican si `algun` valor es `True` en la Series o `todos` los valores son `True`.

In [ ]:
pd.Series([True, False, False]).any()

In [ ]:
pd.Series([True, False, False]).all()

El método `isnull()` retorna una `Series` Booleana con valores `True` donde existe un valor `nan`:

In [ ]:
s.isnull()

Podemos aplicar el método `any` a la matriz retornada en el paso anterior:

In [ ]:
s.isnull().any()

![separator2](https://i.imgur.com/4gX5WFr.png)